# Generated by Django 5.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('ORDER', 'Order'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('order_id', models.CharField(blank=True, help_text='Reference to order for navigation', max_length=20, null=True, verbose_name='Order ID')),
                ('transaction_id', models.CharField(blank=True, help_text='Reference to transaction for navigation', max_length=100, null=True, verbose_name='Transaction ID')),
                ('is_important', models.BooleanField(default=False, help_text='Show as toast notification on frontend', verbose_name='Important')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order_enabled', models.BooleanField(default=True, verbose_name='Order Notifications')),
                ('deposit_enabled', models.BooleanField(default=True, verbose_name='Deposit Notifications')),
                ('withdraw_enabled', models.BooleanField(default=True, verbose_name='Withdraw Notifications')),
                ('system_enabled', models.BooleanField(default=True, verbose_name='System Notifications')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Email Notifications')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram Notifications')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Chat ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_5f7c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_8d3e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_2a9c4e_idx'),
        ),
    ]
