# Generated by Django 5.0 on 2025-11-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload site logo (PNG/SVG recommended)', null=True, upload_to='site/logo/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Upload favicon (PNG/ICO, recommended 32x32 or 64x64)', null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Upload background image for hero section', null=True, upload_to='site/hero/', verbose_name='Hero Background Image')),
                ('hero_background_css', models.CharField(blank=True, default='linear-gradient(to right, #2563eb, #9333ea)', help_text='CSS background value (color or gradient), e.g., linear-gradient(to right, #2563eb, #9333ea)', max_length=500, verbose_name='Hero Background CSS')),
                ('hero_title', models.CharField(default='Fast & Secure Game Top-Up', help_text='Main title in hero section (English)', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.CharField(default='Support 50+ popular games • Top-up in 5 minutes • 24/7 support', help_text='Subtitle/description in hero section (English)', max_length=500, verbose_name='Hero Subtitle')),
                ('hero_primary_button', models.CharField(default='Top Up Now', help_text='Text for primary action button', max_length=50, verbose_name='Primary Button Text')),
                ('hero_secondary_button', models.CharField(default='View Guide', help_text='Text for secondary action button', max_length=50, verbose_name='Secondary Button Text')),
            ],
            options={
                'verbose_name': 'Site Appearance',
                'verbose_name_plural': 'Site Appearance',
            },
        ),
    ]
