# Generated by Django 5.2.8 on 2025-11-13 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Số tiền')),
                ('currency', models.CharField(choices=[('VND', 'VNĐ'), ('USDT', 'USDT')], default='USDT', max_length=10, verbose_name='Loại tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('rejected', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Hash')),
                ('from_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ gửi')),
                ('to_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ nhận')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú admin')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Giao dịch nạp tiền',
                'verbose_name_plural': 'Giao dịch nạp tiền',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_vnd', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Số dư (VNĐ)')),
                ('balance_usdt', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Số dư (USDT)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Ví người dùng',
                'verbose_name_plural': 'Ví người dùng',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Nạp tiền'), ('withdraw', 'Rút tiền'), ('payment', 'Thanh toán'), ('refund', 'Hoàn tiền'), ('bonus', 'Thưởng')], max_length=20, verbose_name='Loại giao dịch')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Số tiền')),
                ('currency', models.CharField(default='VND', max_length=10, verbose_name='Loại tiền')),
                ('balance_before', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Số dư trước')),
                ('balance_after', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Số dư sau')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã tham chiếu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử giao dịch ví',
                'verbose_name_plural': 'Lịch sử giao dịch ví',
                'ordering': ['-created_at'],
            },
        ),
    ]
