# Generated by Django 5.2.8 on 2025-11-13 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Deposit Transaction', 'verbose_name_plural': 'Deposit Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userwallet',
            options={'verbose_name': 'User Wallet', 'verbose_name_plural': 'User Wallets'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wallet Transaction History', 'verbose_name_plural': 'Wallet Transaction History'},
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='balance_vnd',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='balance_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balance (USD)'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Note'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('USDT', 'USDT')], default='USDT', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='From Address'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed At'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='to_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='To Address'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance_usdt',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Balance (USDT)'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Balance After'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Balance Before'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('payment', 'Payment'), ('refund', 'Refund'), ('bonus', 'Bonus')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
