# Generated by Django 5.0 on 2025-11-19 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_server_alter_order_package_in_game_unit_and_more'),
        ('wallets', '0003_convert_to_usd_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in USDT', max_digits=15, verbose_name='Amount (USD)')),
                ('tx_hash', models.CharField(help_text='TronScan transaction hash', max_length=255, unique=True, verbose_name='Transaction Hash')),
                ('from_address', models.CharField(blank=True, help_text='Sender wallet address (optional)', max_length=100, verbose_name='From Address')),
                ('to_address', models.CharField(help_text='Our USDT TRC20 receiving address', max_length=100, verbose_name='To Address')),
                ('status', models.CharField(choices=[('pending_verification', 'Chờ xác minh'), ('confirmed', 'Đã xác nhận'), ('rejected', 'Từ chối')], default='pending_verification', max_length=30, verbose_name='Status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('admin_note', models.TextField(blank=True, help_text='Internal notes for admin', verbose_name='Admin Note')),
                ('auto_paid_order', models.BooleanField(default=False, help_text='Whether this deposit auto-paid the related order', verbose_name='Auto Paid Order')),
                ('related_order', models.ForeignKey(blank=True, help_text='If this deposit is to pay for a specific order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_deposits', to='orders.order', verbose_name='Related Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_crypto_deposits', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Crypto Deposit (USDT TRC20)',
                'verbose_name_plural': 'Crypto Deposits (USDT TRC20)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='wallets_cry_status_a55ae3_idx'), models.Index(fields=['user', '-created_at'], name='wallets_cry_user_id_c33e23_idx')],
            },
        ),
    ]
