# Generated by Django 5.2.8 on 2025-11-13 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='orders/attachments/', verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'File đính kèm',
                'verbose_name_plural': 'File đính kèm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(max_length=20, verbose_name='Trạng thái cũ')),
                ('new_status', models.CharField(max_length=20, verbose_name='Trạng thái mới')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Log trạng thái đơn hàng',
                'verbose_name_plural': 'Log trạng thái đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã đơn hàng')),
                ('game_uid', models.CharField(max_length=200, verbose_name='UID / ID nhân vật')),
                ('game_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên tài khoản game')),
                ('game_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email game')),
                ('game_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT game')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền nạp (VNĐ)')),
                ('price_vnd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá thanh toán (VNĐ)')),
                ('price_usdt', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Giá thanh toán (USDT)')),
                ('payment_method', models.CharField(choices=[('wallet', 'Ví nội bộ'), ('crypto', 'Crypto (USDT)')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_transaction_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Hash')),
                ('status', models.CharField(choices=[('pending_payment', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('canceled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending_payment', max_length=20, verbose_name='Trạng thái')),
                ('customer_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú khách hàng')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú admin')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game', verbose_name='Game')),
                ('game_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gamepackage', verbose_name='Gói nạp')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
