# Generated by Django 5.2.8 on 2025-11-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_vnd',
        ),
        migrations.AddField(
            model_name='order',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (Game Currency)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_usdt',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Price (USDT)'),
        ),
    ]
