# Generated by Django 5.0 on 2025-11-13 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_convert_to_usd_currency'),
        ('orders', '0004_convert_to_usd_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_orders', to='games.game', verbose_name='Game'),
        ),
    ]
