# Generated by Django 5.0 on 2025-11-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='Mã đơn hàng'),
        ),
    ]
