# Generated by Django 5.0 on 2025-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_update_order_for_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='server',
        ),
        migrations.AlterField(
            model_name='order',
            name='package_in_game_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Đơn vị trong game (snapshot)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_name_snapshot',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên gói (snapshot)'),
        ),
    ]
