# Generated by Django 5.2.8 on 2025-11-13 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tên game')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='games/', verbose_name='Ảnh game')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='games/icons/', verbose_name='Icon')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('maintenance', 'Bảo trì'), ('inactive', 'Tạm dừng')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('min_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=12, verbose_name='Số tiền tối thiểu')),
                ('max_amount', models.DecimalField(decimal_places=2, default=10000000, max_digits=12, verbose_name='Số tiền tối đa')),
                ('game_url', models.URLField(blank=True, null=True, verbose_name='Link game')),
                ('requires_server', models.BooleanField(default=False, verbose_name='Yêu cầu chọn server')),
                ('requires_uid', models.BooleanField(default=True, verbose_name='Yêu cầu UID')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tên gói')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị (VNĐ)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán (VNĐ)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giảm giá (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='games.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Gói nạp',
                'verbose_name_plural': 'Gói nạp',
                'ordering': ['display_order', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tên server')),
                ('code', models.CharField(max_length=50, verbose_name='Mã server')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='games.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'Server game',
                'verbose_name_plural': 'Servers game',
                'ordering': ['name'],
                'unique_together': {('game', 'code')},
            },
        ),
    ]
