# Generated by Django 5.0 on 2025-11-18 13:45

import apps.games.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_update_gamepackage_structure'),
        ('orders', '0009_remove_order_server_alter_order_package_in_game_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='game',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='game',
            name='requires_server',
        ),
        migrations.RemoveField(
            model_name='game',
            name='requires_uid',
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, help_text='Chỉ chấp nhận file: .jpg, .jpeg, .png, .webp', null=True, upload_to='games/icons/', validators=[apps.games.models.validate_image_extension], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(help_text='Chỉ chấp nhận file: .jpg, .jpeg, .png, .webp', upload_to='games/', validators=[apps.games.models.validate_image_extension], verbose_name='Ảnh game'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='base_package',
            field=models.ForeignKey(blank=True, help_text='Chỉ dành cho gói bảo hành - chọn gói thường tương ứng', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_packages', to='games.gamepackage', verbose_name='Gói gốc'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='in_game_unit_label',
            field=models.CharField(default='Kim cương', help_text='VD: Kim cương, Vàng, Xu, Diamonds, etc.', max_length=50, verbose_name='Đơn vị trong game'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='name',
            field=models.CharField(help_text='VD: Gói 100 Kim Cương', max_length=200, verbose_name='Tên gói'),
        ),
        migrations.AlterField(
            model_name='gamepackage',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá (USD/USDT)'),
        ),
        migrations.DeleteModel(
            name='GameServer',
        ),
    ]
