# Generated by Django 5.0 on 2025-11-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_convert_package_json_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='introduction',
            field=models.TextField(blank=True, default='', help_text='Giới thiệu chi tiết về game (hỗ trợ HTML)', verbose_name='Giới thiệu chi tiết'),
        ),
    ]
